quickfixj:
  client:
    config: ${classpath:quickfixj-client.cfg}
    jmx-enabled: true
  server:
    config: ${classpath:quickfixj-server.cfg}
    auto-startup: true
    phase: 0
    jmx-enabled: true
    concurrent:
      enabled=true:

server:
  port: 8081

management:
  endpoint:
   quickfixjserver:
      enabled: true
  endpoints:
    web:
      exposure:
        include: quickfixjserver